name: Deploy
on:
  push:
    branches: ['main']
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: write
  issues: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Change base path
        run: sed -i 's/base href="\/"/base href="\/oprima-proposal-commercial\/"/g' ObraPrima.WebUI/wwwroot/index.html
      
      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools
        
      - name: Restore dependencies
        run: dotnet restore
          
      - name: Build
        run: dotnet build ObraPrima.WebUI.csproj -c Release --no-restore
        
      - name: Publish
        run: dotnet publish ObraPrima.WebUI.csproj -c:Release -o docs --nologo
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: 'docs/wwwroot'
          
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4